name: MyProject CI/CD

on:
  push:
    branches:
      - main

env:
  BUILD_ENV: production
  DOCKER_REGISTRY: my-docker-registry.com
  APP_NAME: my-java-app

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize
      run: |
        echo "Initializing pipeline for ${APP_NAME} in ${BUILD_ENV} environment"
        java -version

    - name: Static Analysis - Checkstyle
      run: ./gradlew checkstyleMain

    - name: Static Analysis - Lint
      run: ./gradlew lint

    - name: Build Application
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Generate Code Coverage Report
      run: ./gradlew jacocoTestReport

    - name: Publish Code Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: Code Coverage Report
        path: build/reports/jacoco/index.html

    - name: Build Docker Image
      run: docker build -t ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_ENV} .

    - name: Push Docker Image
      run: docker push ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_ENV}

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/deployment.yaml

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: '**/build/libs/*.jar'

  post:
    always:
      steps:
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: '**/build/libs/*.jar'

    success:
      steps:
      - name: Notify Success
        run: |
          echo 'Pipeline succeeded!'
          echo "The pipeline for ${APP_NAME} succeeded. Build available at ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" | mail -s "Build Success: ${APP_NAME}" team@example.com

    failure:
      steps:
      - name: Notify Failure
        run: |
          echo 'Pipeline failed.'
          echo "The pipeline for ${APP_NAME} failed. Check logs at ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" | mail -s "Build Failed: ${APP_NAME}" team@example.com