stages:
  - checkout
  - build
  - test
  - deploy

variables:
  BUILD_ENV: "production"

checkout-job:
  stage: checkout
  script:
    - git clone $CI_REPOSITORY_URL .

build-job:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  script:
    - ./test.sh
  artifacts:
    paths:
      - artifacts/
  reports:
    junit: reports/**/*.xml

deploy-job:
  stage: deploy
  script:
    - ./deploy.sh

after_script:
  - echo "Pipeline succeeded!"
  - echo "Pipeline failed."