stages:
  - checkout
  - build
  - test
  - deploy

variables:
  BUILD_ENV: "production"

# Optimization: Added 'cache' to speed up subsequent runs by caching dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - node_modules/

checkout-job:
  stage: checkout
  script:
    - git checkout $CI_COMMIT_REF_NAME

build-job:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  dependencies: # Optimization: Specify dependencies to ensure the correct order of job execution
    - build-job
  script:
    - ./test.sh
  artifacts:
    paths:
      - artifacts/
  reports:
    junit: reports/**/*.xml

deploy-job:
  stage: deploy
  dependencies: # Optimization: Specify dependencies to ensure the correct order of job execution
    - test-job
  script:
    - ./deploy.sh