stages:
  - checkout
  - build
  - test
  - deploy

variables:
  BUILD_ENV: "production"

# Optimization: Use caching to speed up the checkout process
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .git/

checkout-job:
  stage: checkout
  script:
    - git clone $CI_REPOSITORY_URL .

build-job:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  script:
    - ./test.sh
  artifacts:
    paths:
      - artifacts/
  reports:
    junit: reports/**/*.xml

deploy-job:
  stage: deploy
  script:
    - ./deploy.sh

# Optimization: Use 'after_script' within each job for better maintainability
after_script:
  - echo "Pipeline succeeded!"
  - echo "Pipeline failed."