name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test  # Optimization: Set environment variable globally for the job

    steps:
      # Optimization: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Optimization: Print environment variable
      - name: Print environment variable
        run: echo "Environment will be : ${{ env.NODE_ENV }}"

      # Optimization: Use setup-node action to ensure correct Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version

      # Optimization: Prune and install npm packages in one step
      - name: Prune and install npm packages
        run: |
          npm prune
          npm install

      # Optimization: Run npm tests
      - name: Run npm tests
        run: npm test

      # Optimization: Build Docker image
      - name: Build Docker image
        run: ./dockerBuild.sh

      # Optimization: Deploy Docker image
      - name: Deploy Docker image
        run: |
          echo 'Push to Repo'
          ./dockerPushToRepo.sh
          echo 'ssh to web server and tell it to pull new image'
          ssh deploy@xxxxx.xxxxx.com running/xxxxxxx/dockerRun.sh

      # Optimization: Cleanup
      - name: Cleanup
        run: |
          echo 'prune and cleanup'
          npm prune
          rm -rf node_modules

      # Optimization: Send success email
      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.your-email.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'project build successful'
          body: 'project build successful'
          to: 'yyyyy@yyyy.com'
          from: 'xxxx@yyyyy.com'

  failure:
    runs-on: ubuntu-latest
    if: failure()

    steps:
      # Optimization: Send failure email
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.your-email.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'project build failed'
          body: "project build error is here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: 'zzzz@yyyyy.com'
          from: 'xxxx@yyyy.com'