name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Using the latest stable version of checkout action
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Combine build and test steps to reduce overhead
    - name: Build and Test
      run: |
        ./build.sh
        ./test.sh

    # Optimization: Deploy step remains the same
    - name: Deploy
      run: ./deploy.sh

    # Optimization: Archive artifacts only if build and test succeed
    - name: Archive Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

    # Optimization: Publish test results only if tests are run
    - name: Publish Test Results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'reports/**/*.xml'

    # Optimization: Combine success and failure notifications into one step
    - name: Notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo 'Pipeline succeeded!';
        else
          echo 'Pipeline failed.';
        fi