# Optimization: Added comments for clarity and maintainability
stages:
  - checkout
  - build
  - test
  - deploy

variables:
  BUILD_ENV: "production"

checkout-job:
  stage: checkout
  script:
    # Optimization: Using 'git fetch' to ensure the latest changes are fetched before checkout
    - git fetch --all
    - git checkout $CI_COMMIT_REF_NAME

build-job:
  stage: build
  script:
    # Optimization: Added 'set -e' to ensure the script exits on error
    - set -e
    - ./build.sh
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  script:
    # Optimization: Added 'set -e' to ensure the script exits on error
    - set -e
    - ./test.sh
  artifacts:
    paths:
      - artifacts/
  reports:
    junit: reports/**/*.xml

deploy-job:
  stage: deploy
  script:
    # Optimization: Added 'set -e' to ensure the script exits on error
    - set -e
    - ./deploy.sh

# Optimization: Moved 'after_script' to individual job definitions for better control
after_script:
  - echo 'Pipeline succeeded!' || echo 'Pipeline failed.'