name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Using the latest version of checkout action for better performance and features
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Grouping build and test steps to improve readability and maintainability
    - name: Build and Test
      run: |
        ./build.sh
        ./test.sh

    # Optimization: Adding a condition to deploy only on successful build and test
    - name: Deploy
      if: success()
      run: ./deploy.sh

    # Optimization: Combining artifact upload steps to reduce redundancy
    - name: Archive Artifacts and Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          '**/target/*.jar'
          'reports/**/*.xml'

    # Optimization: Combining success and failure notifications into a single step for simplicity
    - name: Notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo 'Pipeline succeeded!';
        else
          echo 'Pipeline failed.';
        fi