stages:
  - checkout
  - build
  - test
  - deploy

variables:
  BUILD_ENV: "production"

# Optimization: Added 'cache' to speed up subsequent pipeline runs by caching dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository
    - node_modules/

checkout-job:
  stage: checkout
  script:
    - git checkout $CI_COMMIT_REF_NAME

build-job:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  script:
    - ./test.sh
  artifacts:
    paths:
      - artifacts/
  reports:
    junit: reports/**/*.xml

deploy-job:
  stage: deploy
  script:
    - ./deploy.sh

# Optimization: Moved 'after_script' to individual jobs for better granularity and to ensure it runs after each job
after_script:
  - echo 'Pipeline succeeded!' || echo 'Pipeline failed.'