name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.repo.local=.m2/repository # Optimization: Use local Maven repository to speed up builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: your-username/your-java-project
        ref: main

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3 # Optimization: Cache Maven dependencies to speed up subsequent builds
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

  post:
    always:
      - name: Clean workspace
        run: git clean -fdx

    success:
      - name: Success message
        run: echo 'Build and Test stages successful.'

    failure:
      - name: Failure message
        run: echo 'Build or Test failed.'