name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      # Optimization: Cache dependencies to speed up build process
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install dependencies
      # Optimization: Separate dependency installation step
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_ENV: production

    steps:
    - name: Checkout code
      # Optimization: Ensure code is checked out in deploy job
      uses: actions/checkout@v3

    - name: Deploy
      run: ./deploy.sh

  post:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    steps:
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'reports/**/*.xml'

    - name: Notify Success
      if: success()
      run: echo 'Pipeline succeeded!'

    - name: Notify Failure
      if: failure()
      run: echo 'Pipeline failed.'