name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Checkout code using the latest stable version of the action
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Combine build and test steps to reduce the number of shell invocations
    - name: Build and Test
      run: |
        ./build.sh
        ./test.sh

    # Optimization: Deploy step remains unchanged as it is a separate concern
    - name: Deploy
      run: ./deploy.sh

    # Optimization: Archive artifacts and publish test results in a single step to reduce redundancy
    - name: Archive Artifacts and Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-and-test-artifacts
        path: |
          '**/target/*.jar'
          'reports/**/*.xml'

    # Optimization: Combine success and failure notifications into a single step to reduce redundancy
    - name: Notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo 'Pipeline succeeded!';
        else
          echo 'Pipeline failed.';
        fi