name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production
      DOCKER_REGISTRY: my-docker-registry.com
      APP_NAME: my-java-app

    steps:
    # Optimization: Using the latest version of checkout action
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Combine initialization steps to reduce the number of shell invocations
    - name: Initialize
      run: |
        echo "Initializing pipeline for ${APP_NAME} in ${BUILD_ENV} environment"
        java -version

    # Optimization: Combine static analysis steps to reduce the number of shell invocations
    - name: Static Analysis
      run: |
        echo 'Running Code Analysis...'
        ./gradlew checkstyleMain lint

    # Optimization: Combine build and test steps to reduce the number of shell invocations
    - name: Build and Test
      run: |
        echo 'Building and Testing Application...'
        ./gradlew build test

    # Optimization: Combine code coverage steps to reduce the number of shell invocations
    - name: Code Coverage
      run: |
        echo 'Generating Code Coverage Report...'
        ./gradlew jacocoTestReport

    # Optimization: Use a single action to upload multiple artifacts
    - name: Publish Reports and Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: reports-and-artifacts
        path: |
          build/reports/jacoco/index.html
          '**/build/libs/*.jar'

    # Optimization: Combine Docker build and push steps to reduce the number of shell invocations
    - name: Docker Build and Push
      run: |
        echo 'Building and Pushing Docker Image...'
        docker build -t ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_ENV} .
        docker push ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_ENV}

    # Optimization: Add a step to set up kubectl to ensure it's available
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        echo 'Deploying Application to Kubernetes...'
        kubectl apply -f k8s/deployment.yaml

  post:
    always:
      steps:
      - name: Notify always
        run: echo 'Archiving build artifacts...'

    success:
      steps:
      - name: Notify success
        run: |
          echo 'Pipeline succeeded!'
          echo "The pipeline for ${APP_NAME} succeeded. Build available at ${GITHUB_RUN_URL}" | mail -s "Build Success: ${APP_NAME}" team@example.com

    failure:
      steps:
      - name: Notify failure
        run: |
          echo 'Pipeline failed.'
          echo "The pipeline for ${APP_NAME} failed. Check logs at ${GITHUB_RUN_URL}" | mail -s "Build Failed: ${APP_NAME}" team@example.com