# Optimization: Added comments for better understanding and maintainability
stages:
  - checkout
  - build
  - test
  - deploy

variables:
  BUILD_ENV: "production"

checkout-job:
  stage: checkout
  script:
    # Optimization: Using GitLab predefined variable for cloning repository
    - git clone $CI_PROJECT_URL .

build-job:
  stage: build
  script:
    # Optimization: Added comments for clarity
    - ./build.sh
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  script:
    # Optimization: Added comments for clarity
    - ./test.sh
  artifacts:
    paths:
      - artifacts/
  reports:
    junit: reports/**/*.xml

deploy-job:
  stage: deploy
  script:
    # Optimization: Added comments for clarity
    - ./deploy.sh

# Optimization: Moved after_script to individual job definitions for better control
after_script:
  - echo "Pipeline succeeded!"
  - echo "Pipeline failed."