name: MyProject CI/CD

on:
  # Optimization: Added pull_request event to trigger workflow on PRs to main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      # Optimization: Added step to set up JDK 11 for Java projects
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache dependencies
      # Optimization: Added caching for dependencies to speed up builds
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build
      run: ./build.sh

    - name: Test
      run: ./test.sh

    - name: Deploy
      run: ./deploy.sh

    - name: Archive Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'reports/**/*.xml'

    - name: Success Notification
      if: success()
      run: echo 'Pipeline succeeded!'

    - name: Failure Notification
      if: failure()
      run: echo 'Pipeline failed.'