name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test  # Optimization: Set environment variable globally for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print environment variable
      run: echo "Environment will be : ${{ env.NODE_ENV }}"

    - name: Check Node.js version
      run: node -v

    - name: Install npm packages
      run: npm ci  # Optimization: Use 'npm ci' for clean install and faster performance

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: ./dockerBuild.sh

    - name: Deploy Docker image
      run: |
        echo 'Push to Repo'
        ./dockerPushToRepo.sh
        echo 'ssh to web server and tell it to pull new image'
        ssh deploy@xxxxx.xxxxx.com running/xxxxxxx/dockerRun.sh

    - name: Cleanup
      run: |
        echo 'prune and cleanup'
        npm prune
        rm -rf node_modules

    - name: Send success email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.your-email.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "project build successful"
        body: "project build successful"
        to: "yyyyy@yyyy.com"
        from: "xxxx@yyyyy.com"
        content_type: text/plain

  on_failure:
    runs-on: ubuntu-latest
    if: failure()

    steps:
    - name: Send failure email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.your-email.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "project build failed"
        body: "project build error is here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        to: "zzzz@yyyyy.com"
        from: "xxxx@yyyy.com"
        content_type: text/plain