name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Using the latest version of checkout action for better performance and features
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Combining build and test steps to reduce the number of shell invocations
    - name: Build and Test
      run: |
        ./build.sh
        ./test.sh

    # Optimization: Using a single upload-artifact action to handle both build artifacts and test results
    - name: Archive Artifacts and Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-and-results
        path: |
          '**/target/*.jar'
          'reports/**/*.xml'

    # Optimization: Combining success and failure messages into a single step to reduce redundancy
    - name: Post Pipeline Message
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo 'Pipeline succeeded!';
        else
          echo 'Pipeline failed.';
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Optimization: Using the latest version of checkout action for better performance and features
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: ./deploy.sh