name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Checkout code step remains unchanged as it is necessary to fetch the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Combine build and test steps to reduce the number of shell invocations
    - name: Build and Test
      run: |
        ./build.sh
        ./test.sh

    # Optimization: Archive artifacts only if the build and test steps succeed
    - name: Archive Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

    # Optimization: Publish test results only if the test step succeeds
    - name: Publish Test Results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'reports/**/*.xml'

    # Optimization: Echo messages combined into a single step to reduce the number of steps
    - name: Echo Pipeline Status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo 'Pipeline succeeded!'
        else
          echo 'Pipeline failed.'
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Checkout code step remains unchanged as it is necessary to fetch the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Deploy step remains unchanged as it is necessary for deployment
    - name: Deploy
      run: ./deploy.sh