name: MyProject CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production
      DOCKER_REGISTRY: my-docker-registry.com
      APP_NAME: my-java-app

    steps:
    # Optimization: Checkout code using the latest version of the action
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Combine initialization steps to reduce the number of shell invocations
    - name: Initialize
      run: |
        echo "Initializing pipeline for ${APP_NAME} in ${BUILD_ENV} environment"
        java -version

    # Optimization: Combine static analysis steps to reduce the number of shell invocations
    - name: Static Analysis
      run: |
        echo 'Running Code Analysis...'
        ./gradlew checkstyleMain lint

    # Optimization: Combine build and test steps to reduce the number of shell invocations
    - name: Build and Test
      run: |
        echo 'Building and Testing Application...'
        ./gradlew build test

    # Optimization: Generate code coverage report
    - name: Code Coverage
      run: |
        echo 'Generating Code Coverage Report...'
        ./gradlew jacocoTestReport

    # Optimization: Publish code coverage report using the latest version of the action
    - name: Publish Code Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: build/reports/jacoco/index.html

    # Optimization: Combine Docker build and push steps to reduce the number of shell invocations
    - name: Docker Build and Push
      run: |
        echo 'Building and Pushing Docker Image...'
        docker build -t ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_ENV} .
        docker push ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_ENV}

    # Optimization: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        echo 'Deploying Application to Kubernetes...'
        kubectl apply -f k8s/deployment.yaml

    # Optimization: Archive build artifacts using the latest version of the action
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/build/libs/*.jar'

  post:
    always:
      steps:
      # Optimization: Archive build artifacts using the latest version of the action
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: '**/build/libs/*.jar'

    success:
      steps:
      # Optimization: Notify success with a single echo command
      - name: Notify Success
        run: |
          echo 'Pipeline succeeded!'
          echo "The pipeline for ${APP_NAME} succeeded. Build available at ${GITHUB_RUN_URL}" | mail -s "Build Success: ${APP_NAME}" team@example.com

    failure:
      steps:
      # Optimization: Notify failure with a single echo command
      - name: Notify Failure
        run: |
          echo 'Pipeline failed.'
          echo "The pipeline for ${APP_NAME} failed. Check logs at ${GITHUB_RUN_URL}" | mail -s "Build Failed: ${APP_NAME}" team@example.com