name: MyProject CI/CD

on:
  # Optimization: Added pull_request event to trigger the workflow on PRs as well
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production

    steps:
    # Optimization: Checkout code step remains the same as it is essential
    - name: Checkout code
      uses: actions/checkout@v3

    # Optimization: Cache dependencies to speed up build times
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Optimization: Build step remains the same
    - name: Build
      run: ./build.sh

    # Optimization: Test step remains the same
    - name: Test
      run: ./test.sh

    # Optimization: Deploy step remains the same
    - name: Deploy
      run: ./deploy.sh

    # Optimization: Archive build artifacts step remains the same
    - name: Archive Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: '**/target/*.jar'

    # Optimization: Publish test results step remains the same
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'reports/**/*.xml'

    # Optimization: Combined success and failure notifications into one step
    - name: Notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo 'Pipeline succeeded!'
        else
          echo 'Pipeline failed.'
        fi