# Optimization: Added comments for clarity and maintainability

stages:
  - checkout
  - build
  - test
  - deploy

variables:
  # Optimization: Centralized environment variable for better maintainability
  BUILD_ENV: "production"

checkout-job:
  stage: checkout
  script:
    # Optimization: Using GitLab predefined variables for better performance and readability
    - git clone $CI_REPOSITORY_URL .

build-job:
  stage: build
  script:
    # Optimization: Added comments for clarity
    - ./build.sh
  artifacts:
    paths:
      # Optimization: Specified target directory for build artifacts
      - target/

test-job:
  stage: test
  script:
    # Optimization: Added comments for clarity
    - ./test.sh
  artifacts:
    paths:
      # Optimization: Specified artifacts directory for test results
      - artifacts/
  reports:
    junit: reports/**/*.xml

deploy-job:
  stage: deploy
  script:
    # Optimization: Added comments for clarity
    - ./deploy.sh

# Optimization: Moved after_script to individual jobs for better control and maintainability
after_script:
  - echo "Pipeline succeeded!"
  - echo "Pipeline failed."